#!/usr/bin/env node

import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = path.join(projectRoot, "src");
const publicRoot = path.join(projectRoot, "public");
const distRoot = path.join(projectRoot, "dist");

const entries = {
  "background/service-worker.js": [
    "shared/defaults.js",
    "shared/messages.js",
    "shared/validation.js",
    "storage/settings-repository.js",
    "background/service-worker.js"
  ],
  "content/bootstrap.js": [
    "shared/defaults.js",
    "shared/validation.js",
    "content/adapters/selectors.js",
    "content/core/normalizer.js",
    "content/core/heuristics.js",
    "content/core/rule-engine.js",
    "content/adapters/dom-utils.js",
    "content/adapters/base-adapter.js",
    "content/adapters/entity-parsers.js",
    "content/adapters/video-card-adapter.js",
    "content/adapters/home-adapter.js",
    "content/adapters/page-matcher.js",
    "content/adapters/search-adapter.js",
    "content/adapters/video-page-adapter.js",
    "content/controllers/danmaku-controller.js",
    "content/renderers/filter-renderer.js",
    "content/route-observer.js",
    "content/bootstrap.js"
  ],
  "popup/index.js": [
    "shared/client.js",
    "shared/defaults.js",
    "popup/index.js"
  ],
  "options/index.js": [
    "shared/client.js",
    "shared/defaults.js",
    "shared/validation.js",
    "content/core/normalizer.js",
    "content/core/heuristics.js",
    "content/core/rule-engine.js",
    "options/index.js"
  ]
};

function stripModuleSyntax(source) {
  return source
    .replace(/^import .*;\n/gmu, "")
    .replace(/^export /gmu, "")
    .trim();
}

function indent(source) {
  return source.split("\n").map((line) => line ? `  ${line}` : "").join("\n");
}

async function createBundle(outputRelativePath, modulePaths) {
  const modules = [];

  for (const modulePath of modulePaths) {
    const source = await readFile(path.join(sourceRoot, modulePath), "utf8");
    modules.push(`// ${modulePath}\n${stripModuleSyntax(source)}`);
  }

  const output = [
    "/* BiliClean v0.1.4 — generated by scripts/build.mjs. */",
    '"use strict";',
    "(() => {",
    indent(modules.join("\n\n")),
    "})();",
    ""
  ].join("\n");

  const outputPath = path.join(distRoot, outputRelativePath);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

await rm(distRoot, { recursive: true, force: true });
await cp(publicRoot, distRoot, { recursive: true });

for (const [outputPath, modulePaths] of Object.entries(entries)) {
  await createBundle(outputPath, modulePaths);
}

console.log(`Built ${Object.keys(entries).length} bundles in ${path.relative(projectRoot, distRoot)}/`);
